services:
  app:
    depends_on:
      - mariadb
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=toor
      - DB_NAME=hoyo-codes-api
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=hoyo-codes-api